name: Build ISO

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
    - 'vm/**'
  workflow_dispatch:

jobs:
  build-ova:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm archiso git base-devel arch-install-scripts awk dosfstools e2fsprogs erofs-utils findutils grub gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools edk2-ovmf qemu shellcheck python-docutils gdm virtualbox

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Where am i
        run: |
          ls
      
      - name: Create work and out
        run: |
          mkdir work
          mkdir out

      - name: Create symlinks
        run: |
          ln -s /usr/lib/systemd/system/vboxservice.service vm/airootfs/etc/systemd/system/multi-user.target.wants/vboxservice.service
          ln -sf /usr/lib/systemd/system/gdm.service vm/airootfs/etc/systemd/system/display-manager.service

      - name: Build ISO
        run: |
          mkarchiso -v -w work -o out vm/

      - name: Upload OVA artifact
        uses: actions/upload-artifact@v4
        with:
          name: owlArchIso
          path: out/*.iso

  release:
    needs: build-ova
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download OVA artifact
        uses: actions/download-artifact@v4
        with:
          name: owlArchIso
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./out

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: ./out/*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
